# Generated by Django 3.2.8 on 2022-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='user_category',
            options={'verbose_name_plural': 'User Job Descriptions'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_aveage_experience',
            field=models.CharField(max_length=40, verbose_name='average job experience'),
        ),
    ]
